version: '1'

services:
  backend:
    build: ./Backend
    container_name: shatellBackend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Backend:/app
    ports:
      - ${DJANGO_MAP_PORT}:8000
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - shatellNetwork

  frontend:
    build: ./Frontend
    container_name: shatellFrontend
    volumes:
      - ./Frontend:/frontend
    ports:
      - ${REACT_MAP_PORT}:5173
    networks:
      - shatellNetwork

  db:
    image: postgres:latest
    container_name: shatellPostgresDB
    volumes:
      - shatellPostgresData:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_MAP_PORT}:5432
    env_file:
      - ./.env
    networks:
      - shatellNetwork

volumes:
  shatellPostgresData:

networks:
  shatellNetwork:
