# Generated by Django 5.0.6 on 2024-05-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_waitingregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('national_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='WaitingRegister',
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='password',
            field=models.TextField(),
        ),
    ]
