# Generated by Django 5.0.6 on 2024-05-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userinfo_delete_waitingregister_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='national_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
